# Generated by Django 3.1.5 on 2021-08-22 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 16, 46, 57, 276723), verbose_name='添加时间'),
        ),
    ]
