# Generated by Django 3.1.5 on 2021-08-23 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210822_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 23, 16, 59, 39, 456000), verbose_name='添加时间'),
        ),
    ]
