# Generated by Django 3.1.5 on 2021-09-06 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210823_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 6, 22, 7, 9, 696349), verbose_name='添加时间'),
        ),
    ]
