# Generated by Django 3.1.5 on 2021-10-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodscategorybrand_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsimage',
            name='image_url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='图片路径'),
        ),
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='image',
            field=models.ImageField(max_length=200, upload_to='brands/'),
        ),
    ]
