# Generated by Django 3.1.5 on 2021-08-23 16:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0002_auto_20210822_1646'),
        ('trade', '0002_auto_20210822_1642'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShppingCart',
            new_name='ShoppingCart',
        ),
    ]
