# Generated by Django 3.1.5 on 2021-11-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0003_auto_20211119_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleavingmessage',
            name='msg_type',
            field=models.IntegerField(choices=[(1, '留言'), (2, '投诉'), (3, '询问'), (4, '售后'), (5, '求购')], default=1, help_text='留言类型: 1(留言),2(投诉),3(询问),4(售后),5(求购)', verbose_name='留言类型'),
        ),
    ]
