# Generated by Django 3.1.5 on 2021-11-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20210928_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_mount',
            field=models.FloatField(default=0.0, verbose_name='支付金额'),
        ),
    ]
