# Generated by Django 3.1.5 on 2021-11-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20211126_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='signer_mobile',
            new_name='singer_mobile',
        ),
    ]
